CS460/HWK4/Homework4/Homework4/Controllers/ColorController.cs
using System.Web.Mvc;
using System.Drawing;
using System;

namespace Homework4.Controllers
{
    public class ColorController : Controller
    {
        /// <summary>
        /// GET for ColorMixer
        /// </summary>
        /// <returns>The view - ColorMixer.cshtml</returns>
        public ActionResult ColorMixer()
        {
            /* Set the flag to show the boxes to false initially */
            ViewBag.ShowBoxes = false;

            /* Return the view */
            return View();
        }

        /// <summary>
        /// POST for ColorMixer. Gets the values from the textboxes and generates a new
        /// color by adding the ARGB color channels together.
        /// </summary>
        /// <param name="firstColor">The color code from the first textbox.</param>
        /// <param name="secondColor">The color code from the second textbox.</param>
        /// <returns>The view - ColorMixer.cshtml - with the bool flag in the appropriate state.</returns>
        [HttpPost]
        public ActionResult ColorMixer(string firstColor, string secondColor)
        {
            /* Set the flag to show the boxes to false initially */
            ViewBag.ShowBoxes = false;

            /* Make sure the fields aren't null before proceeding */
            if (firstColor != null && secondColor != null)
            {
                /* Convert the strings into Color objects so we can add them together */
                Color rgbColorOne = ColorTranslator.FromHtml(firstColor);
                Color rgbColorTwo = ColorTranslator.FromHtml(secondColor);

                /* Add each channel together from the two colors */
                int finalColorRed = rgbColorOne.R + rgbColorTwo.R;
                int finalColorGreen = rgbColorOne.G + rgbColorTwo.G;
                int finalColorBlue = rgbColorOne.B + rgbColorTwo.B;

                /* 
                 * Subtract 255 from any values greater than 255, effectively 
                 * wrapping around from 0. This allows for more color combinations
                 * that don't result in plain white.
                 */
                if (finalColorRed > 255) finalColorRed -= 255;
                if (finalColorGreen > 255) finalColorGreen -= 255;
                if (finalColorBlue > 255) finalColorBlue -= 255;

                /* Construct the mixture using the channels we just calculated */
                string finalColor = ColorTranslator.ToHtml(Color.FromArgb(finalColorRed, finalColorGreen, finalColorBlue));

                /* Set the background information for each of the boxes */
                ViewBag.FirstColorBox = "background: " + firstColor + ";";
                ViewBag.SecondColorBox = "background: " + secondColor + ";";
                ViewBag.FinalColorBox = "background: " + finalColor + ";";

                /* Change the flag to show the boxes */
                ViewBag.ShowBoxes = true;
            }

            /* Return the view, with or without the boxes visible */
            return View();
        }
    }
}

CS460/HWK4/Homework4/Homework4/Controllers/HomeController.cs
using System;
using System.Web.Mvc;

namespace Homework4.Controllers
{
    public class HomeController : Controller
    {
        /// <summary>
        /// GET for Home.cshtml
        /// </summary>
        /// <returns>The view - Home.cshtml</returns>
        public ActionResult Home()
        {
            return View();
        }
        
        /// <summary>
        /// GET for Converter.cshtml
        /// </summary>
        /// <returns>The view - Converter.cshtml</returns>
        public ActionResult Converter()
        {            
            double miles = 0;
            string userInput = Request["miles_to_convert"];
            string unit = Request["units"];

            /* Attempt to parse the input we grabbed from the form */
            if (Double.TryParse(userInput, out miles))
            {
                /* If we parsed it successfully, do the appropriate conversion */
                switch (unit)
                {
                    case "millimeters":                        
                        miles = miles * Properties.Settings.Default.MILLIMETERS_PER_MILE; ;
                        break;
                    case "centimeters":
                        miles = miles * Properties.Settings.Default.CENTIMETERS_PER_MILE;
                        break;
                    case "meters":
                        miles = miles * Properties.Settings.Default.METERS_PER_MILE;
                        break;
                    case "kilometers":
                        miles = miles * Properties.Settings.Default.KILOMETERS_PER_MILE;
                        break;
                    default:
                        break;
                }

                /* Construct a message to display relating to the conversion */
                ViewBag.Message = (userInput + " mile(s) is equal to " + miles + " " + unit + ".");
            }
            
            /* Return the view (Converter.cshtml) */
            return View();            
        }
    }
}

CS460/HWK4/Homework4/Homework4/Views/Color/ColorMixer.cshtml
@{
    ViewBag.Title = "ColorMixer";
}

<!DOCTYPE html>

<html>

<body>
    <!-- Page header -->
    <div class="jumbotron">
        <h1>Mix Two Colors Together</h1>
    </div>

    <!-- Prompt with instructions for the user -->
    <h4>Enter two color codes in HTML hexadecimal format (#ABC -or- #AABBCC):</h4>

    @using (@Html.BeginForm("ColorMixer", "Color", FormMethod.Post))
    {
        <div class="container">
            <div class="box-container col-md-4 col-xs-12">
                <!-- Prompt for the first color -->
                <section>
                    <div style="float: left;">
                        @Html.Label("First color:")
                        @Html.TextBox("firstColor", @Request["firstColor"], new
                   {
                       @class = "form-control",
                       id = "firstColor",
                       placeholder = "#AABBCC",
                       name = "firstColor",
                       pattern = "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                       title = "HTML hexadecimal color code (#AABBCC)",
                       required = "required",
                       autocomplete = "off"
                   })
                        <!-- Create a color picker under the first color box -->
                        <input type="color" onchange="setFirstColor(this)" onkeyup="setFirstColor(this)"
                               class="btn btn-default" value="@Request["firstColor"]">
                    </div>

                    <br style="clear: both;" />

                </section>

                <!-- Prompt for the second color -->
                <section>
                    <div style="float: left;">
                        @Html.Label("Second color:")
                        @Html.TextBox("secondColor", @Request["secondColor"], new
                   {
                       @class = "form-control",
                       id = "secondColor",
                       placeholder = "#AABBCC",
                       name = "secondColor",
                       pattern = "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$",
                       title = "HTML hexadecimal color code (#AABBCC)",
                       required = "required",
                       autocomplete = "off"
                   })
                        <!-- Create a color picker under the second color box -->
                        <input type="color" onchange="setSecondColor(this)" onkeyup="setSecondColor(this)"
                               class="btn btn-default" value="@Request["secondColor"]">
                    </div>
                </section>
            </div>

            <!-- Function calls to handle setting textbox values from the above color pickers. -->
            <script>
                function setFirstColor(colorValue) {
                    document.getElementById("firstColor").value = colorValue.value;
                }

                function setSecondColor(colorValue) {
                    document.getElementById("secondColor").value = colorValue.value;
                }
            </script>
            <!-- END OF FUN / EDUCATIONAL EXERCISE -->

            <!-- Submit button for mixing the two colors provided by the user -->
            <div>
                <input id="btnSubmitColors" class="btn btn-default submitted" type="submit" value="Mix Colors" />
            </div>

        </div>

        <!-- If the flag has been set to true in the controller, show the color boxes -->
        if (ViewBag.ShowBoxes)
        {
            <div class="colorBox" style="@ViewBag.FirstColorBox"></div>
            <label class="colorBoxLabel">+</label>
            <div class="colorBox" style="@ViewBag.SecondColorBox"></div>
            <label class="colorBoxLabel">=</label>
            <div class="colorBox" style="@ViewBag.FinalColorBox"></div>
        }
    }
</body>
</html>

CS460/HWK4/Homework4/Homework4/Views/Home/Converter.cshtml
@{
    ViewBag.Title = "Converter";
}

<body>
    <div class="jumbotron">
        <h1>Convert Miles to Metric Units</h1>
    </div>

    <!-- Set up the containers in order to position the elements how we want them -->
    <div class="container">
        <form method="get" action="Converter">
            <div class="box-container col-md-4 col-xs-12">
                <fieldset>
                    <legend>Miles:</legend>
                    <div>
                        <!-- Create the input field, set a default a prompt, and limit input length -->
                        <input id="userInput" type="text" name="miles_to_convert" pattern="^[0-9]\d*(\.\d+)?$" autocomplete="off"
                               required="required" title="A positive number." placeholder="Enter a positive integer..." maxlength="27">
                        <button id="btnConvert" class="btn btn-default">&raquo; Convert &laquo;</button>
                    </div>
                </fieldset>
            </div>

            <!-- RADIO BUTTONS START -->
            <div id="radioButtons" class="box-container col-md-4 col-xs-12">
                <fieldset>
                    <legend>Select unit to convert to:</legend>
                    <div>
                        <input type="radio" id="millimeters"
                               name="units" value="millimeters" checked />
                        <label class="radioLabel" for="millimeters">Millimeters</label>
                    </div>
                    <div>
                        <input type="radio" id="centimeters"
                               name="units" value="centimeters" />
                        <label class="radioLabel" for="centimeters">Centimeters</label>
                    </div>
                    <div>
                        <input type="radio" id="meters"
                               name="units" value="meters" />
                        <label class="radioLabel" for="meters">Meters</label>
                    </div>
                    <div>
                        <input type="radio" id="kilometers"
                               name="units" value="kilometers" />
                        <label class="radioLabel" for="kilometers">Kilometers</label>
                    </div>
                </fieldset>
            </div>
            <!-- RADIO BUTTONS END -->
        </form>

        <label id="conversionResults">@ViewBag.Message</label>

    </div>

</body>

CS460/HWK4/Homework4/Homework4/Views/Home/Home.cshtml
@{
    ViewBag.Title = "Home Page";
}

<body>
    <!-- Page header -->
    <div class="jumbotron text-center">
        <h1>CS460 Homework IV</h1>
        <p class="lead">This is the main page for the fourth homework assignment in CS460.</p>
        <!-- Insert a button to the project's repository -->
        <p><a id="btnViewRepo" href="https://github.com/brockv/brockv.github.io/tree/master/CS460/HWK4" class="btn btn-primary btn-lg">&raquo; View repository &laquo;</a></p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <!-- Section to hold information for the Converter -->
            <h2>Miles to Metric Converter</h2>
            <p>Converter utilizing query strings to send information to the server where the calculations are performed.</p>
            <p><a class="btn btn-default btnGoToPages" href="http://localhost:53616/Home/Converter">&raquo; Converter &laquo;</a></p>
        </div>
        <div class="col-md-4">
            <!-- Section to hold information for the Color Mixer -->
            <h2>Color Mixer</h2>
            <p>Combine two HTML color codes to create an exciting new color!</p>
            <p><a class="btn btn-default btnGoToPages" href="http://localhost:53616/Color/ColorMixer">&raquo; Color Mixer &laquo;</a></p>
        </div>
    </div>
</body>